// src/hooks/useAnalyticsEmail.ts
// Builds styled HTML email reports for each analytics tab

import * as FileSystem from 'expo-file-system';
import * as MailComposer from 'expo-mail-composer';
import { Alert } from 'react-native';
import { addToOutbox } from '../storage/reportOutbox';
import type {
  PosPerf, PlayerTrend, QuarterMomentum,
  PairCombination, CPTurnoverMatch, CoachInsight,
  PlayerBasic, MatchBasic,
} from './useAnalytics';

const POSITIONS = ['GS','GA','WA','C','WD','GD','GK'];

function scoreColor(score: number) {
  if (score === 0) return '#1e293b';
  if (score >= 70) return '#15803d';
  if (score >= 50) return '#ca8a04';
  return '#dc2626';
}

const CSS = `
  body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;margin:0;padding:24px;background:#0b1120;color:#e2e8f0;}
  h1{font-size:22px;font-weight:900;margin:0 0 4px;}
  h2{font-size:16px;font-weight:800;margin:18px 0 8px;color:#94a3b8;}
  .sub{color:#64748b;font-size:13px;margin-bottom:20px;}
  table{width:100%;border-collapse:collapse;margin-bottom:16px;}
  th{background:#0f172a;color:#94a3b8;font-size:12px;font-weight:700;padding:8px 10px;text-align:left;border-bottom:1px solid #1e293b;}
  td{padding:8px 10px;border-bottom:1px solid #1e293b;font-size:13px;color:#e2e8f0;}
  tr:nth-child(even) td{background:#10172a;}
  .badge{display:inline-block;padding:2px 8px;border-radius:20px;font-size:11px;font-weight:800;}
  .good{color:#22c55e;} .warn{color:#f59e0b;} .bad{color:#ef4444;}
  .chip{display:inline-block;background:#1e293b;border-radius:8px;padding:6px 12px;margin:4px;text-align:center;}
  .chip-val{font-size:20px;font-weight:900;display:block;}
  .chip-lbl{font-size:10px;color:#64748b;font-weight:700;}
  .insight{border-left:3px solid #0a84ff;background:#0a84ff11;border-radius:8px;padding:10px 14px;margin-bottom:8px;font-size:14px;line-height:1.5;}
  .insight.pos{border-left-color:#22c55e;background:#22c55e11;}
  .insight.warn{border-left-color:#f59e0b;background:#f59e0b11;}
  .cell{display:inline-block;width:52px;height:48px;border-radius:6px;text-align:center;vertical-align:middle;font-size:12px;font-weight:900;line-height:1.2;padding-top:6px;}
  .footer{margin-top:32px;padding-top:12px;border-top:1px solid #1e293b;color:#334155;font-size:11px;}
`;

function footer(scope: string) {
  return `<div class="footer">Generated by Netball Coach App · ${new Date().toLocaleDateString()} · ${scope}</div>`;
}

// ── 1. Insights HTML ──────────────────────────────────────────────────────────
export function buildInsightsHtml(opts: {
  insights: CoachInsight[];
  posPerf: PosPerf[];
  momentum: QuarterMomentum[];
  cpTurnover: CPTurnoverMatch[];
  matches: MatchBasic[];
  scope: string;
}) {
  const { insights, posPerf, momentum, cpTurnover, matches, scope } = opts;
  const totalGoals = posPerf.filter(r => ['GS','GA'].includes(r.position)).reduce((a, r) => a + r.goals, 0);
  const totalAttempts = posPerf.filter(r => ['GS','GA'].includes(r.position)).reduce((a, r) => a + r.attempts, 0);
  const totalPens = cpTurnover.reduce((a, m) => a + m.totalPenalties, 0);
  const avgCP = cpTurnover.length > 0 ? Math.round(cpTurnover.reduce((a, m) => a + m.cpConversionPct, 0) / cpTurnover.length) : 0;
  const wins = momentum.filter(m => m.finalDiff > 0).length;
  const shootPct = totalAttempts > 0 ? Math.round(100 * totalGoals / totalAttempts) : 0;

  const insightRows = insights.map(i => `
    <div class="insight ${i.type === 'positive' ? 'pos' : i.type === 'warning' ? 'warn' : ''}">
      ${i.emoji} ${i.text}
    </div>`).join('');

  const chips = [
    ['Matches', matches.length, ''],
    ['Wins', wins, wins >= matches.length * 0.5 ? 'good' : 'warn'],
    ['Total Goals', totalGoals, ''],
    ['Shooting %', totalAttempts > 0 ? `${shootPct}%` : '—', shootPct >= 75 ? 'good' : shootPct >= 60 ? 'warn' : 'bad'],
    ['CP Conv%', avgCP > 0 ? `${avgCP}%` : '—', avgCP >= 65 ? 'good' : avgCP >= 50 ? 'warn' : 'bad'],
    ['Penalties', totalPens, totalPens < 10 ? 'good' : totalPens < 20 ? 'warn' : 'bad'],
  ].map(([lbl, val, cls]) => `<span class="chip"><span class="chip-val ${cls}">${val}</span><span class="chip-lbl">${lbl}</span></span>`).join('');

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${CSS}</style></head><body>
    <h1>📊 Analytics — Coach Insights</h1>
    <div class="sub">${scope}</div>
    <h2>Quick Stats</h2>
    <div style="margin-bottom:16px">${chips}</div>
    <h2>Coach Summary</h2>
    ${insightRows || '<p style="color:#64748b">Not enough data yet.</p>'}
    ${footer(scope)}
  </body></html>`;
}

// ── 2. Position × Player HTML ────────────────────────────────────────────────
export function buildHeatmapHtml(opts: {
  posPerf: PosPerf[];
  players: PlayerBasic[];
  scope: string;
}) {
  const { posPerf, players, scope } = opts;
  const perfMap: Record<string, PosPerf> = {};
  posPerf.forEach(r => { perfMap[`${r.playerId}::${r.position}`] = r; });
  const activePlayers = players.filter(p => posPerf.some(r => r.playerId === p.id));

  const headerCells = POSITIONS.map(p => `<th style="text-align:center">${p}</th>`).join('');

  const rows = activePlayers.map(player => {
    const cells = POSITIONS.map(pos => {
      const perf = perfMap[`${player.id}::${pos}`];
      if (!perf) return `<td style="background:#0f172a;text-align:center">—</td>`;
      const bg = scoreColor(perf.score);
      const txt = perf.score > 55 ? '#fff' : '#000';
      const shootLine = perf.attempts > 0 ? `<br><span style="font-size:10px;opacity:0.8">${perf.goalPct}%</span>` : '';
      const qLine = `<br><span style="font-size:10px;opacity:0.7">×${perf.quarters}</span>`;
      return `<td style="background:${bg};color:${txt};text-align:center;font-weight:900">${perf.score}${shootLine}${qLine}</td>`;
    }).join('');
    return `<tr><td style="font-weight:700">${player.first_name} ${player.last_name}</td>${cells}</tr>`;
  }).join('');

  // Detail table
  const detailRows = posPerf
    .sort((a, b) => b.score - a.score)
    .map(r => {
      const p = players.find(pl => pl.id === r.playerId);
      const name = p ? `${p.first_name} ${p.last_name}` : r.playerId;
      const cls = r.score >= 70 ? 'good' : r.score >= 50 ? 'warn' : 'bad';
      return `<tr>
        <td>${name}</td><td>${r.position}</td><td>${r.quarters}</td>
        <td class="${cls}" style="font-weight:900">${r.score}</td>
        <td>${r.attempts > 0 ? `${r.goalPct}%` : '—'}</td>
        <td>${r.goals}</td><td>${r.feeds}</td>
        <td class="${r.penalties > 3 ? 'bad' : ''}">${r.penalties}</td>
        <td>${r.interceptions}</td>
      </tr>`;
    }).join('');

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${CSS} td,th{min-width:40px;}</style></head><body>
    <h1>📍 Player × Position Analysis</h1>
    <div class="sub">${scope}</div>
    <div style="margin-bottom:8px;font-size:12px;color:#64748b">
      Score 0–100: <span style="color:#15803d">■</span> Strong (70+) 
      <span style="color:#ca8a04">■</span> Average (50–70) 
      <span style="color:#dc2626">■</span> Weak (&lt;50)
    </div>
    <div style="overflow-x:auto">
      <table><thead><tr><th>Player</th>${headerCells}</tr></thead><tbody>${rows}</tbody></table>
    </div>
    <h2>Full Detail</h2>
    <table>
      <thead><tr><th>Player</th><th>Pos</th><th>Qtrs</th><th>Score</th><th>Goal%</th><th>Goals</th><th>Feeds</th><th>Pens</th><th>Intcpts</th></tr></thead>
      <tbody>${detailRows}</tbody>
    </table>
    ${footer(scope)}
  </body></html>`;
}

// ── 3. Player Trends HTML ────────────────────────────────────────────────────
export function buildTrendsHtml(opts: {
  playerTrends: PlayerTrend[];
  players: PlayerBasic[];
  scope: string;
}) {
  const { playerTrends, players, scope } = opts;
  const playerById = Object.fromEntries(players.map(p => [p.id, p]));

  const sections = playerTrends.map(trend => {
    const player = playerById[trend.playerId];
    if (!player || trend.matches.length === 0) return '';
    const name = `${player.first_name} ${player.last_name}`;

    const rows = trend.matches.map(m => {
      const gpCls = m.attempts > 0 ? (m.goalPct >= 75 ? 'good' : m.goalPct >= 60 ? 'warn' : 'bad') : '';
      return `<tr>
        <td>${m.matchLabel}</td><td>${m.matchDate}</td>
        <td>${m.quartersPlayed}</td>
        <td class="${gpCls}" style="font-weight:800">${m.attempts > 0 ? `${m.goalPct}%` : '—'}</td>
        <td>${m.goals}</td>
        <td class="${m.penalties > 3 ? 'bad' : ''}">${m.penalties}</td>
        <td>${m.feeds}</td><td>${m.assists}</td><td>${m.interceptions}</td>
      </tr>`;
    }).join('');

    // Trend direction (last 3 vs first 3 goalPct)
    const gps = trend.matches.filter(m => m.attempts > 0).map(m => m.goalPct);
    let trendNote = '';
    if (gps.length >= 4) {
      const earlyAvg = gps.slice(0, Math.floor(gps.length / 2)).reduce((a, b) => a + b, 0) / Math.floor(gps.length / 2);
      const lateAvg  = gps.slice(Math.ceil(gps.length / 2)).reduce((a, b) => a + b, 0) / gps.slice(Math.ceil(gps.length / 2)).length;
      const diff = lateAvg - earlyAvg;
      if (diff > 5) trendNote = `<div class="insight pos">📈 ${name} is improving — shooting % up ${diff.toFixed(1)}pts over the season</div>`;
      else if (diff < -5) trendNote = `<div class="insight warn">📉 ${name}'s shooting % is down ${Math.abs(diff).toFixed(1)}pts — worth addressing</div>`;
    }

    return `
      <h2>${name}</h2>
      ${trendNote}
      <table>
        <thead><tr><th>Match</th><th>Date</th><th>Qtrs</th><th>Goal%</th><th>Goals</th><th>Pens</th><th>Feeds</th><th>Assists</th><th>Intcpts</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>`;
  }).filter(Boolean).join('');

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${CSS}</style></head><body>
    <h1>📈 Player Season Trends</h1>
    <div class="sub">${scope}</div>
    ${sections || '<p style="color:#64748b">No trend data yet.</p>'}
    ${footer(scope)}
  </body></html>`;
}

// ── 4. Quarter Momentum HTML ─────────────────────────────────────────────────
export function buildMomentumHtml(opts: {
  momentum: QuarterMomentum[];
  scope: string;
}) {
  const { momentum, scope } = opts;

  const avgDiffs = [1,2,3,4].map(q => {
    const key = `q${q}Diff` as keyof QuarterMomentum;
    if (!momentum.length) return 0;
    return momentum.reduce((a, m) => a + (m[key] as number), 0) / momentum.length;
  });

  const avgRow = avgDiffs.map((d, i) => {
    const cls = d > 0 ? 'good' : d < 0 ? 'bad' : '';
    return `<td class="${cls}" style="font-weight:900;text-align:center">${d > 0 ? `+${d.toFixed(1)}` : d.toFixed(1)}</td>`;
  }).join('');

  const matchRows = [...momentum].reverse().map(m => {
    const resultCls = m.finalDiff > 0 ? 'good' : m.finalDiff < 0 ? 'bad' : '';
    const label = m.finalDiff > 0 ? `W +${m.finalDiff}` : m.finalDiff < 0 ? `L ${m.finalDiff}` : 'D 0';
    const diffs = [m.q1Diff, m.q2Diff, m.q3Diff, m.q4Diff].map(d => {
      const cls = d > 0 ? 'good' : d < 0 ? 'bad' : '';
      return `<td class="${cls}" style="font-weight:800;text-align:center">${d > 0 ? `+${d}` : d}</td>`;
    }).join('');
    return `<tr><td>${m.matchLabel}</td>${diffs}<td class="${resultCls}" style="font-weight:900">${label}</td></tr>`;
  }).join('');

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${CSS}</style></head><body>
    <h1>⚡ Quarter Momentum</h1>
    <div class="sub">${scope}</div>
    <h2>Season Average by Quarter</h2>
    <table>
      <thead><tr><th></th><th style="text-align:center">Q1</th><th style="text-align:center">Q2</th><th style="text-align:center">Q3</th><th style="text-align:center">Q4</th></tr></thead>
      <tbody><tr><td style="font-weight:700">Avg Diff</td>${avgRow}</tr></tbody>
    </table>
    <h2>Per-Match Breakdown</h2>
    <table>
      <thead><tr><th>Match</th><th style="text-align:center">Q1</th><th style="text-align:center">Q2</th><th style="text-align:center">Q3</th><th style="text-align:center">Q4</th><th>Result</th></tr></thead>
      <tbody>${matchRows}</tbody>
    </table>
    ${footer(scope)}
  </body></html>`;
}

// ── 5. Combinations HTML ─────────────────────────────────────────────────────
export function buildCombinationsHtml(opts: {
  pairs: PairCombination[];
  players: PlayerBasic[];
  scope: string;
}) {
  const { pairs, players, scope } = opts;
  const playerById = Object.fromEntries(players.map(p => [p.id, p]));

  const rows = pairs.map((pair, i) => {
    const [pa, pb] = pair.playerIds.map(id => {
      const p = playerById[id];
      return p ? `${p.first_name} ${p.last_name}` : id;
    });
    const diffCls = pair.scoreDiff > 0 ? 'good' : pair.scoreDiff < 0 ? 'bad' : '';
    return `<tr>
      <td style="font-weight:900">#${i+1}</td>
      <td style="font-weight:700">${pa}</td>
      <td style="font-weight:700">${pb}</td>
      <td style="text-align:center">${pair.quartersTogther}</td>
      <td style="text-align:center">${pair.homeGoals}</td>
      <td class="${diffCls}" style="font-weight:900;text-align:center">${pair.scoreDiff > 0 ? `+${pair.scoreDiff}` : pair.scoreDiff}</td>
    </tr>`;
  }).join('');

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${CSS}</style></head><body>
    <h1>🤝 Best On-Court Combinations</h1>
    <div class="sub">${scope}</div>
    <p style="color:#64748b;font-size:13px">Ranked by average score difference per quarter when these players share the court. Requires ≥2 quarters together.</p>
    <table>
      <thead><tr><th>Rank</th><th>Player A</th><th>Player B</th><th style="text-align:center">Qtrs Together</th><th style="text-align:center">Goals Scored</th><th style="text-align:center">Avg Score Diff</th></tr></thead>
      <tbody>${rows || '<tr><td colspan="6" style="color:#64748b;text-align:center">Not enough data yet</td></tr>'}</tbody>
    </table>
    ${footer(scope)}
  </body></html>`;
}

// ── 6. CP & Turnover HTML ────────────────────────────────────────────────────
export function buildCPTOHtml(opts: {
  cpTurnover: CPTurnoverMatch[];
  scope: string;
}) {
  const { cpTurnover, scope } = opts;

  const avgCP = cpTurnover.length ? Math.round(cpTurnover.reduce((a, m) => a + m.cpConversionPct, 0) / cpTurnover.length) : 0;
  const avgTO = cpTurnover.filter(m => m.toWon > 0).length
    ? Math.round(cpTurnover.filter(m => m.toWon > 0).reduce((a, m) => a + m.toConversionPct, 0) / cpTurnover.filter(m => m.toWon > 0).length) : 0;

  const penTotals: Record<string, number> = {};
  cpTurnover.forEach(m => Object.entries(m.penaltyByPosition).forEach(([pos, c]) => { penTotals[pos] = (penTotals[pos] || 0) + c; }));
  const penRows = Object.entries(penTotals).sort((a, b) => b[1] - a[1]).map(([pos, c]) =>
    `<tr><td>${pos}</td><td class="${c > 5 ? 'bad' : c > 3 ? 'warn' : 'good'}" style="font-weight:800">${c}</td></tr>`
  ).join('');

  const matchRows = [...cpTurnover].reverse().map(m => {
    const cpCls = m.cpConversionPct >= 65 ? 'good' : m.cpConversionPct >= 50 ? 'warn' : 'bad';
    const toCls = m.toConversionPct >= 50 ? 'good' : 'warn';
    return `<tr>
      <td>${m.matchLabel}</td><td>${m.matchDate}</td>
      <td class="${cpCls}" style="font-weight:800">${m.cpToScore + m.cpNoScore > 0 ? `${m.cpConversionPct}%` : '—'}</td>
      <td>${m.cpToScore}</td><td>${m.cpNoScore}</td>
      <td class="${toCls}" style="font-weight:800">${m.toWon > 0 ? `${m.toConversionPct}%` : '—'}</td>
      <td>${m.toWon}</td><td>${m.toScored}</td>
      <td class="${m.totalPenalties > 8 ? 'bad' : ''}" style="font-weight:800">${m.totalPenalties}</td>
    </tr>`;
  }).join('');

  const summaryChips = [
    ['Avg CP%', avgCP > 0 ? `${avgCP}%` : '—', avgCP >= 65 ? 'good' : avgCP >= 50 ? 'warn' : 'bad'],
    ['Avg TO%', avgTO > 0 ? `${avgTO}%` : '—', ''],
    ['Matches', cpTurnover.length, ''],
  ].map(([lbl, val, cls]) => `<span class="chip"><span class="chip-val ${cls}">${val}</span><span class="chip-lbl">${lbl}</span></span>`).join('');

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${CSS}</style></head><body>
    <h1>🔄 Centre Pass & Turnover</h1>
    <div class="sub">${scope}</div>
    <div style="margin-bottom:16px">${summaryChips}</div>
    ${penRows ? `
      <h2>Penalty Hotspots by Position</h2>
      <table><thead><tr><th>Position</th><th>Total Penalties</th></tr></thead><tbody>${penRows}</tbody></table>
    ` : ''}
    <h2>Per-Match Breakdown</h2>
    <table>
      <thead><tr><th>Match</th><th>Date</th><th>CP%</th><th>CP✓</th><th>CP✗</th><th>TO%</th><th>TO Won</th><th>TO Scored</th><th>Pens</th></tr></thead>
      <tbody>${matchRows || '<tr><td colspan="9" style="color:#64748b;text-align:center">No data yet</td></tr>'}</tbody>
    </table>
    ${footer(scope)}
  </body></html>`;
}

// ── Shared email sender ───────────────────────────────────────────────────────
export async function sendAnalyticsEmail(opts: {
  html: string;
  subject: string;
  filename: string;
  addresses: string[];
}) {
  const { html, subject, filename, addresses } = opts;
  const uri = `${FileSystem.cacheDirectory}${filename}.html`;
  await FileSystem.writeAsStringAsync(uri, html, { encoding: 'utf8' });

  const isAvail = await MailComposer.isAvailableAsync();
  if (isAvail) {
    await MailComposer.composeAsync({
      recipients: addresses,
      subject,
      body: `Please find the analytics report attached.\n\nGenerated by Netball Coach App on ${new Date().toLocaleDateString()}.`,
      attachments: [uri],
    });
  } else {
    // Queue it in the report outbox
    await addToOutbox({
      matchId: filename,
      heading: subject,
      sub: new Date().toLocaleDateString(),
      addresses,
      csvUri: '',
      htmlUri: uri,
    });
    Alert.alert('Queued', 'Mail not available. Report queued and will send when possible.');
  }
}
